### ISSUE TITLE
Ferry times are not being properly calculated

### ISSUE THREAD

**Issue by Eric-Sparks** [GIScience/openrouteservice#1037]
I'm noticing that ORS isn't calculating ferry duration times correctly.

For example, the [Cedar Island-Ocracoke Ferry](https://www.openstreetmap.org/way/16460171), which has a [duration tag](https://wiki.openstreetmap.org/wiki/Key:duration) of 02:15, is being calculated as having a duration of 3 hours, 36 minutes.

> On: Cedar Island-Ocracoke Ferry, NC 12
> ↑ Continue straight onto Cedar Island-Ocracoke Ferry, NC 12
> Distance: 36.0 km
> access_time 3 hour(s) 36 min 11 s 

Another example, the [Hatteras-Ocracoke Ferry](https://www.openstreetmap.org/way/16611155), which has a [duration tag](https://wiki.openstreetmap.org/wiki/Key:duration) of 01:00, is being calculated as having a duration of 3 hours, 6 minutes.

> On: Ferry Access, NC 12
> ↖ Turn slight left onto Ferry Access, NC 12
> Distance: 15.7 km
> access_time 3 hour(s) 6 min 26 s

Is it possible to use the [duration tag](https://wiki.openstreetmap.org/wiki/Key:duration) when it is available instead of trying to calculate the time based on distance?

**Comment by aoles** [comment]
Thanks for reaching out! Let me apologize for not responding earlier, vacation season.. 🏖️

Actually, ORS already takes into account `duration` OSM tag. However, apart from the pure travel time additional overhead of loading/unloading and waiting time for the ferry to be available is added on top to provide more realistic estimates. This is done by a heuristic which reduces the ferry travel speed computed from its travel time and travel distance by a factor of `1.4`, see [the original GraphHopper implementation](https://github.com/GIScience/graphhopper/blob/ors_0.13/core/src/main/java/com/graphhopper/routing/util/AbstractFlagEncoder.java#L397-L399).

However, there is a serious flaw in the above implementation: the use of "as the crow flies" distance between the start and end point coordinates of the ferry connection rather than its actual length based on way geometry. This systematically underestimates the length of the ferry route and results in lower ferry travel speed estimate. It becomes a problem once the travel time of a requested route is being computed as then the actual distance based on the full geometry is considered. In fact, this is particularly evident for the Hatteras-Ocracoke Ferry. According to the mentioned heuristic the extended travel time should be around 1h 24m, while the reported one is over twice as long ([3h 05m](https://classic-maps.openrouteservice.org/directions?n1=35.195387&n2=-75.762258&n3=15&a=35.208074,-75.702667,35.189557,-75.780087&b=0&c=0&k1=en-US&k2=km)). The reason for it is that while the beeline distance between the 2 ferry terminals is around 7 km, the actual route the ferry takes is 15.5 km long.

![image](https://user-images.githubusercontent.com/6545356/130986864-b848c871-b2e8-4d8c-9dc9-2944d48cc608.png)


I will have a look into improving ferry travel time estimates, so stay tuned!

Cheers,
Andrzej
