### ISSUE TITLE
`access=destination` speed of 5 km/h too low?

### ISSUE THREAD

**Issue by koebi** [GIScience/openrouteservice#1061]
A user commentary in our [forum](https://ask.openrouteservice.org/t/route-returns-very-slow-driving-rate/3151) reported unusually long drive times on a highway that turned out to be tagged with `access:destination`.

The ors uses a speed of 5 km/h for such routes, compare https://github.com/GIScience/openrouteservice/blob/37fca1d1b6bf1203deb69c4a1ec6633248a725f8/openrouteservice/src/main/java/org/heigit/ors/routing/graphhopper/extensions/flagencoders/VehicleFlagEncoder.java#L157. 

This particular highway has a maxspeed of 45 mph, but the more general question is whether a speed of 5 km/h is justified for roads with `access:destination`.

**Comment by HendrikLeuschner** [comment]
This has been an ongoing topic for a long time. The speed is set to be 5kmh to keep the routing from using it like a normal way (discouraging by making it very costly in terms of time), while still allowing to reach a destination that is on this path.
You'd need to build a system where you already know that this is going to be your destination in order to avoid this problem. Surely doable (using e.g. virtual edges) but never done and we just used the GH solution.
In this case my question is: why is the highway tagged as `access:destination`?

**Comment by sfendrich** [comment]
IMO the question why the road is tagged `access:destination` is irrelevant, because this is a very common situation which ORS should handle correctly. Overriding `max_speed` with 5km/h is obviously not the right thing to do. BTW, GH returns a sensible travel time: https://graphhopper.com/maps/?point=35.7011%2C-82.377&point=35.665%2C-82.4486&locale=en-US&elevation=true&profile=car&use_miles=false&layer=Omniscale. We'll have to figure out whether (a) recommended weighting or (b) access-restrictions are good ways to resolve this issue. Any other ideas?

**Comment by HendrikLeuschner** [comment]
If GH have a good solution for this problem, we should use it. Our original solution is based on our GH version afaik.

**Comment by aoles** [comment]
I think the best way of addressing the issue of `access:destination` roads  is to use a priority-type weighting, see https://github.com/GIScience/openrouteservice/issues/705.

**Comment by TheGreatRefrigerator** [comment]
Would an option be to get the next point on the graph that is not `destination` and do a normal route (not using any destination ways anymore) to there adding the parts for the destination part on top?

**Comment by MichaelsJP** [comment]
related to #253

**Comment by TheGreatRefrigerator** [comment]
take a look at fast iso benchmarks for this

**Comment by MichaelsJP** [comment]
Yup. Fast-Isochrones are affected by the same isochrones calculations as the normal ones. So, we need to revisit those tests once a first fix is in place.
