### ISSUE TITLE
Maximum height of road that is not a tunnel

### ISSUE THREAD

**Issue by orson-69** [GIScience/openrouteservice#1064]
I apologize, not knowing English I used Google Translate

I tried to do the navigation indicated in this Link
```
https://maps.openrouteservice.org/#/directions/Via%20Flaminia%20415,Rimini,RN,Italia/Viale%20Viareggio%207,Rimini,RN,Italia/data/55,130,32,198,15,97,4,224,38,9,96,59,2,24,5,192,166,6,113,0,184,64,70,0,152,3,160,13,144,129,152,0,224,29,128,6,10,108,38,167,15,192,78,0,104,1,102,248,186,216,15,173,223,21,82,249,75,112,13,196,76,190,110,1,88,235,115,174,202,149,118,132,219,113,231,193,130,170,117,232,83,161,33,66,194,33,56,128,128,1,213,60,8,137,176,229,0,11,202,174,202,149,118,132,219,113,231,193,130,170,117,232,83,161,33,66,194,33,56,128,128,1,213,60,8,137,176,229,0,11,202,11,91,92,19,174,222,139,130,130,139,130,139,130,139,130,139,130,139,130,139,130,139,130,139,130,130,139,130,139,130,139,130,130,13,15,0,6,228,128,14,96,11,64,1,111,19,21,98,15,238,136,30,141,14,136,134,14,23,135,153,9,233,239,155,14,139,1,151,96,228,226,234,15,228,26,30,128,15,171,108,141,12,137,224,210,7,153,138,141,22,7,92,235,138,12,158,143,15,28,154,139,129,76,72,77,102,24,143,26,140,155,138,76,64,173,96,14,233,61,59,51,143,61,178,3,191,11,6,183,60,65,77,108,156,134,233,230,139,136,28,130,25,142,128,11,229,245,244,0,0
```
---
The system allowed me to drive a road with Maxheight = 3.1m even though my vehicle is 3.2m tall

I think the problem is related to the fact that the road is not a tunnel, in fact with the tunnels it filters the results well, giving the right path.

I think it is good that it is good that the system takes into account the Maxheight parameter also on normal roads and not only in tunnels.
In fact this is the case of a road that passes under a bridge, it is not correct to map it as a Tunnel

**Comment by koebi** [comment]
Hey,

this seems to indeed be a bug - [this request](https://maps.openrouteservice.org/#/directions/Via%20Flaminia%20417,Rimini,RN,Italy/Viale%20Viareggio%207,Rimini,RN,Italy/data/55,130,32,198,15,97,4,224,38,9,96,59,2,24,5,192,166,6,113,0,184,64,70,0,152,3,160,13,144,128,88,0,101,32,14,90,5,103,32,102,1,57,159,213,128,104,40,184,171,9,80,107,89,133,102,85,88,7,100,16,192,55,17,50,248,197,49,231,202,179,97,13,152,130,226,2,0,7,84,240,34,38,195,148,0,47,40,1,109,115,229,43,191,116,8,0,205,224,1,183,75,132,44,104,240,1,185,32,3,152,2,208,0,89,7,248,232,129,59,160,187,163,67,162,33,129,121,226,38,67,91,89,38,195,162,195,68,25,24,153,154,129,58,184,123,160,3,235,235,35,67,35,91,20,130,38,98,161,249,130,22,154,226,129,135,163,193,5,134,162,227,51,16,82,233,135,32,91,89,162,224,187,35,186,99,160,2,249,45,45,0,0) routes via [this road](https://www.openstreetmap.org/way/980853700), which is tagged with `maxheight:3.1`, which seems to not be considered.

**Comment by sfendrich** [comment]
It seems that the concerned road has been edited recently and, therefore, the data might have not arrived in the graph yet.

**Comment by koebi** [comment]
Yeah, that seems to be the problem here - I missed that :(
I found [a different example](https://maps.openrouteservice.org/#/directions/Schlierbacher%20Landstra%C3%9Fe%209,Heidelberg,BW,Germany/J%C3%A4gerpfad,Heidelberg,BW,Germany/data/55,130,32,198,15,97,4,224,38,9,96,59,2,24,5,192,166,6,113,0,184,64,14,0,232,7,96,5,152,128,216,6,98,160,6,1,57,232,21,133,251,136,17,128,26,83,236,52,246,123,225,160,9,131,144,170,244,3,113,19,47,150,187,9,196,171,10,161,86,190,10,221,123,247,36,190,176,250,236,91,241,9,196,4,0,14,169,224,68,77,135,40,0,94,80,2,218,231,111,140,197,232,16,1,155,192,1,183,69,193,5,134,135,128,3,114,64,7,48,5,160,0,182,136,141,49,6,247,69,247,70,135,68,67,6,11,194,204,129,113,118,205,135,69,129,76,182,181,183,181,6,243,244,15,64,7,208,182,70,134,65,113,169,2,204,197,71,11,2,171,181,197,7,143,71,134,143,141,69,194,164,36,241,7,142,68,113,115,69,197,246,64,12,199,64,5,246,222,218,0) where height makes a difference, so it seems _maxheight_ is respected :))

**Comment by orson-69** [comment]
Thanks.
Sorry for the wrong report
