### ISSUE TITLE
Consolidate RequestHandlers

### ISSUE THREAD

**Issue by HendrikLeuschner** [GIScience/openrouteservice#1067]
Citing @aoles :

> It appears to me that there is massive code duplication across `MatrixRequestHandler`, `RouteRequestHandler` and `GenericRequestHandler`. For example, the `convertRouteProfileType` method here is the same as the corresponding one in the other two classes. I think it would make sense to refactor things to have a common upstream method implementation in `GenericRequestHandler` from which this class could inherit. The same applies for a lot of other methods from `MatrixRequestHandler` such as `convertAvoidAreas, convertAvoidCountries, convertFeatureTypes`, etc

I had to copy over some methods from the request handlers to handle options for the matrix. There is no generic solution implemented, so there is a lot of duplication. This should be addressed.

**Comment by koebi** [comment]
Refactoring `RouteRequestHandler` worked without too much trouble.

Currently, `MatrixRequestHandler` isn't instantiated anywhere, but uses only static methods.
All calls to code in `MatrixRequestHandler` result from a single `MatrixRequestHandler.generateMatrixFromRequest()`-call, similar to the single `RouteRequestHandler().generateRouteFromRequest()`-call for routing.

Is there any upside to using only static methods vs using instance methods?
The `RequestHandler`s don't have any static fields, and only one instance that ever gets created, so I don't quite see why this is happening anyways…

**Comment by koebi** [comment]
I got abit of input from @aoles about this:

> If a given method does not depend on any of its class fields and relies only on data passed through it's arguments then it is a good candidate for a static method. I guess static methods avoid some object-related overhead and their calls might be better optimized by the compiler. In particular, the code of some short static methods could be easily inlined to avoid function calls.
So personally I think static methods should be chosen over instance methods if the design allows for it

The problem here is, that much of the duplication differs only in the error codes used.
Calls from `MatrixRequestHandler` should use `MatrixErrorCodes`, calls from `RoutingRequestHandler` should use `RoutingErrorCodes`

Since we want to inherit from the `GenericHandler`-class to avoid duplication, I don't see any option beyond parsing `Routing`- and `MatrixErrorCodes` to the `errorCodes`-field from the `GenericHandler`-class use that.

**Comment by koebi** [comment]
There is also a lot of Code Duplication in `RouteRequestOptions` and `MatrixRequestOptions` - they only differ in one field:
`RouteRequestOptions` has `round_trip` and `MatrixRequestOptions` has `dynamic_speeds`.
We could probably refactor all duplicates into a generic `RequestOptions`-class, but I'm not sure whether this would greatly increase clarity of the underlying code.

In similar fashion, all `*Request`s have `id` and `profile` that could be refactored into a generic `Request`-class.

**Comment by aoles** [comment]
I believe most of the code duplication in these classes comes from the focus on fast delivery in first place rather than maintainability in long run. If you are already on it I strongly encourage you to clean up a bit.

**Comment by sfendrich** [comment]
If it makes so much trouble, please postpone this refactoring until after the Graphhopper upgrade. 

Concerning static methods: In general, I would say that a static method is a code smell. If a method does not touch the fields of an object, why should it be related to it? However, in Java static methods are often used to encompass the lack of first class functions. For example the standard library class "Math" does not describe a real object, but serves as a namespace for a collection of functions. Similarly, static methods are often used in helper and utility, which by themselves should make you rethink your design.

While the performance considerations are valid to some degree, I am not a big fan of such micro-optimizations. The JVM has sophisticated **run time** optimization strategies, which make it almost impossible to benchmark manual micro-optimizations properly.

**Comment by koebi** [comment]
It doesn't make much trouble - I'm just stumbling over how things are done and am wondering if there is a particular reason I don't know of or if I can just assume historic reasons and continue as I feel is correct :)

**Comment by koebi** [comment]
Regarding a refactoring of the `*Request` and `*RequestOptions`, I'd just go forward with this and we see whether we like what comes up?
I'd do that in a separate PR, to keep things clean. We can move forward with this, I have marked the branch as _Ready for Review_

**Comment by koebi** [comment]
As a short writeup of the discussion about the way forward with @takb and @sfendrich:

API v3.0 is far in the future and will mostly concern the API output rather than the input. Whether OGC compliance is something we want for ors remains to be seen.

Given that, it makes sense to clean up as much as possible. The vision would be to get rid of the `*RequestHandler`-classes, as they don't do anything (as evidenced by the `static`ness of all methods in the `MatrixRequestHandler`). Most of the methods of these classes could become methods of their respective `*Request`-class.
In this process, `Request`-fields common to both `RouteRequest` and `MatrixRequest` and `RequestOption`-fields common to both `RouteRequestOptions` and `MatrixRequestOptions` should be refactored into a general `Request` and `RequestOptions`-class, which would provide a place for methods used in the `GenericHandler`.

To not get lost in this process, first the current PR will be finished and resolved. There are a few questions to be resolved and there is a bit more cleanup to be done which will happen first.

Next, the `CentralityRequestHandler` will be refactored, since it is mostly independent of the rest of the code touched so far, but structured the same as the other `*RequestHandler`s. This will provide a good test case to see what issues will be faced in refactoring all other `Handler`s.

Then, the `IsochroneRequestHandler` will be refactored, for the same reasons as with `CentralityRequestHandler`.

Last, the `MatrixRequestHandler` and `RoutingRequestHandler` will be refactored, since they overlap by quite a bit.

**Comment by koebi** [comment]
This issue is being used to keep track of the ongoing refactoring stated above.
