### ISSUE TITLE
ORS data is not sufficiently up-to-date

### ISSUE THREAD

**Issue by ManDay** [GIScience/openrouteservice#1157]
This is becoming somewhat of a chronic issue in my experience. It was reported before in #868 and closed but this seems to remain a recurring problem. Highways are not accounted for by the router on maps.openrouteservice.org even after weeks and months. Current example [here](https://www.openstreetmap.org/way/256727089), although I think it's not helpful to solve this on a per-case basis. There seems to be something chronically wrong, unless weeks of delay were indeed by-spec.

**Comment by koebi** [comment]
Hey,

this is a due to the processes at work in getting changes from the OSM to the ors. In short, stuff happens on a weekly schedule and in the best case the expected time is about two weeks.
Any step in the process is bound to go wrong at some point, which will lead to delays of a week per error.

As we speak, the graph builders are rebuilding the planet file, so it should be as up to date as it gets within the week.

In this particular example, the issue was with the md5 hashes of the planet file not being up to date.

We know it's unfortunate, but ultimately a consequence of the massive size of data available in the osm.

**Comment by koebi** [comment]
Hey,

you can find some more info [in our backend documentation](https://giscience.github.io/openrouteservice/Frequently-Asked-Questions.html).

I'd hope that clears it up a bit more.
