### ISSUE TITLE
Discourage routing of road bikes on tracktypes below grade 1

### ISSUE THREAD

**Issue by aoles** [GIScience/openrouteservice#1173]
See the [original post ](https://ask.openrouteservice.org/t/profile-roadbike-selects-grade2-often/3901) on the ask forum.

**Comment by marq24** [comment]
I hope with my replies in the forum this issue can be closed...
1)'st When using "shortest" Profile's make almost no difference -> that's correct - since "applied" speeds (per highway type & surface) will not have an effect
2) "shorter/faster" route (via the A20 bridge) will include gravel sections (that the road bike profile tries to avoid if possible at any case (handled internally as "pushing section")

**Comment by aoles** [comment]
Thanks a lot @marq24 for taking the lead in the discussion on the forum and clarifying the observed routing behavior.
