### ISSUE TITLE
Reach calculation: ignore access option

### ISSUE THREAD

**Issue by Hedaja** [GIScience/openrouteservice#1193]
Hi and thanks for the awesome service.

Having an option to disable access restrictions during a reach analysis would be beneficial. For example for firefighters it might not be too important if something is a private road so having a drop down menu (like for avoid) with different options for access=customer/private/no would be nice.

In this example one could take the private shortcut in an emergency. Which would extend the reach towards the west quite significantly.
https://bit.ly/3mXOjea

**Comment by koebi** [comment]
Hey,

currently, access restrictions are considered at graph build time. For there to be an option similar to `avoid ferries`, one would have to implement a new `EdgeFilter` and make access parsing conditional, depending on this new option.
We will most probably refrain from doing so, since ways with `access=customer/private/no` are tagged as that for a reason: They are not accessible to the public, unlike our public routing, matrix and reachability services.

The easier way to solve this would be to create a new profile modeling an emergency vehicle such as police, firefighters or ambulances. Previous work has been done on this in the `EmergencyVehicleFlagEncoder`, but this is probably properly outdated.
In addition, such a new profile would not be running on our public services for resource reasons and since such a profile is again not available to the public.

Best regards

**Comment by takb** [comment]
Superseded by #1398
