### ISSUE TITLE
{car, hgv}-directions and car-matrix find route, but hgv-matrix doesn't 

### ISSUE THREAD

**Issue by koebi** [GIScience/openrouteservice#1198]
This was reported [in the forum](https://ask.openrouteservice.org/t/error-6099-in-matrix-calculation-with-hgv-profile/3993/6) - for the same locations, directions finds car and hgv routes, and matrix finds a car-matrix, but no hgv-matrix.

**Comment by aoles** [comment]
I think the problem has been introduced in https://github.com/GIScience/openrouteservice/pull/1126. This would explain why the issue is only observed on master and not with the current release. It needs further investigation at which point [the new approach](https://github.com/GIScience/openrouteservice/issues/816#issuecomment-1035127497) fails and whether it doesn't work with CH routing in general, or maybe the issue is specific to RPHAST matrix algorithm.
