### ISSUE TITLE
Graph doesn't build if nodes are too far from each other

### ISSUE THREAD

**Issue by MichaelsJP** [GIScience/openrouteservice#1351]
As mentioned in #1300, the graph build fails in version 7.x in cases nodes on an edge are too far from each other.

The error is mentioned in this comment: https://github.com/GIScience/openrouteservice/issues/1300#issuecomment-1470428242

Error: 

> java.lang.IllegalStateException: Suspicious distance for edge: 5156 99021-3837 255.159 vs. 408.49538894896665, difference: -153.33638894896666

The error is thrown here:

> https://github.com/GIScience/graphhopper/blob/v4.3.1/core/src/main/java/com/graphhopper/reader/osm/OSMReader.java#L923

**Comment by koebi** [comment]
[This](https://github.com/GIScience/graphhopper/commit/7881b5cccc09f1e825e0c67a8bfb6325869dfa96) is the commit that introduces the method in question and [this](https://github.com/graphhopper/graphhopper/pull/2221) is the corresponding PR that has quite a bit of explanation on what is going on - maybe that helps :)

**Comment by takb** [comment]
The errors reported in the referenced comment were caused by an actual bug in the GH code. The lines in `ORSReader` that are supposed to handle invalid node references were failing in cases where an OSM way had a) multiple segments handled as separate edges with b) at least one segment with at least one pillar node and c) another separate segment that is processed later with the first pillar node being invalid. 
Will prepare a release on the GH fork and then a PR here.

**Comment by aoles** [comment]
Any idea whether this bug has been fixed in GH by now?

**Comment by takb** [comment]
The relevant code has been refactored quite a bit and distributed over multiple classes meanwhile, I couldn't really make out if the current GH code still has it. We could just run a file with a known problematic way in current GH, but I don't know if it's worth the time...

EDIT: @sfendrich just ran a test file with known problems with current GH and it builds ok.
