### ISSUE TITLE
Handle warning regarding transient dependencies

### ISSUE THREAD

**Issue by takb** [GIScience/openrouteservice#1383]
#### Here's what I think could be improved
Address the following warning 
```
03 Apr 12:35:57 WARN [springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer] - 

Found multiple occurrences of org.json.JSONObject on the class path:

	file:/home/taki/dev/openrouteservice/openrouteservice/target/classes/org/json/JSONObject.class
	jar:file:/home/taki/.m2/repository/com/vaadin/external/google/android-json/0.0.20131108.vaadin1/android-json-0.0.20131108.vaadin1.jar!/org/json/JSONObject.class
	jar:file:/home/taki/.m2/repository/org/json/json/20230227/json-20230227.jar!/org/json/JSONObject.class

You may wish to exclude one of them to ensure predictable runtime behavior 
```

**Comment by MichaelsJP** [comment]
Yup. Can reproduce. 
We could manually exclude `android-json-0.0.20131108.vaadin1.jar` since it's not needed anywhere. As far as I know.

**Comment by MichaelsJP** [comment]
I excluded the android-json. It's one step closer. `org.json` includes further adjustments.
We've a hard-coded and very outdated version of that package directly in our source code at https://github.com/GIScience/openrouteservice/tree/master/openrouteservice/src/main/java/org/json. 

For a clean fix, we should see how relevant that still is and what of that we can replace by the native `org.json` package from maven.

**Comment by MichaelsJP** [comment]
I made it work now, but it's not nice. It's just a workaround and doesn't feel good having multiple org.json and org.json.simple imports in a single file.

The org.json.simple package is mostly used for spring-boot response objects. When comparing the API-Endpoints, it's a mix of Jackson annotations (automatic JSON serialization) and org.json.simple usage. We should probably remove org.json.simple completely and construct response objects purely with Jackson and dedicated POJOs.

**Comment by MichaelsJP** [comment]
Since this is bigger than expected, I created a few more issues to cover certain tasks in smaller chunks.

- (this one) removes the old and redundant version of the native JSON library to solve the transient dependency problem
- (this one) excludes the unused library `android-json` from `org.skyscreamer.jsonassert`which introduces a JsonObject as well.
- [1395](https://github.com/GIScience/openrouteservice/issues/1395) reduces the used JSON libraries to just either `org.json` or òrg.json.json-simple`, and `jackson`. Currently, `org.json.json-simple ` as well as `org.json.json` are used in different scenarios across the project. This should be replaced by clear POJOs with `jackson` annotations where possible (mostly in the API context, (de)serializing POJOs) and decide on one of the json packages.
