### ISSUE TITLE
extra_info not accounted for in latest version

### ISSUE THREAD

**Issue by louisondumont** [GIScience/openrouteservice#1425]
In the latest version, "extras" aren't being returned even when you ask for them with the "extra_info" option.

This resulted in me being unable to properly use my private instance for my intended use.

The public API worked perfectly though. On the same query, the public API would return "extras" and not my private API. The graphs were built properly and ors-config looked just fine.

You can replicate this error by simply setting up the latest version and requesting extras in 'extra_info'. Nothing will be returned.

The temporary SOLUTION I found: use the v6.8.1 branch (same as public API version). Then it works just fine.

Someone somewhere implemented a code since 6.8.1 and latest that broke the extras feature.

**Comment by MichaelsJP** [comment]
@louisondumont Thanks for reporting. We'll investigate that.

**Comment by takb** [comment]
So I've been looking into this (sorry it took us a while to find time to do so), and with latest code as well as last release version code I get the expected extra info results from my local instance. It would have been a surprise otherwise, since our integration tests contain checks on extra info being returned for our test data.

To investigate further we'd need to know a bit more specifics, like how your local instance is set up (docker or native, what source data, config file) and the exact query that is causing the observed problem.

**Comment by sfendrich** [comment]
Closing due to lack of feedback.
