### ISSUE TITLE
Support bicycle=destination for bike profiles

### ISSUE THREAD

**Issue by waldyrious** [GIScience/openrouteservice#1782]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature/Enhancement Proposal

The bike routing should allow routing through paths marked with "bicycle=destination". For example, [this route](https://maps.openrouteservice.org/#/directions/R%20Jose%20Vidal%20Da%20Costa%2013,Braga,Portugal/R%20Dr%20Augusto%20Cesar%20Cerqueira%20Gomes%20123,Braga,Portugal/data/55,130,32,198,15,97,4,224,38,9,96,59,2,24,5,192,166,6,113,0,184,64,90,0,56,3,160,5,148,129,24,6,96,21,130,128,216,104,9,130,210,106,176,194,1,164,184,230,4,226,160,1,137,189,38,165,234,148,36,201,128,110,34,101,41,85,37,94,144,154,117,11,42,163,194,159,42,12,218,16,220,127,133,33,164,65,113,1,0,3,170,120,17,19,97,202,0,23,148,0,182,184,43,246,187,122,2,0,12,222,0,6,221,23,28,0,19,204,20,41,0,28,223,26,29,30,32,21,212,57,26,10,196,0,61,8,61,25,49,12,2,47,25,50,19,211,221,17,22,29,22,4,0,23,222,168,0,0) should follow this sequence of ways: [1262007841](https://www.openstreetmap.org/way/1262007841), [1262007844](https://www.openstreetmap.org/way/1262007844), [1262007834](https://www.openstreetmap.org/way/1262007834), [1262007838](https://www.openstreetmap.org/way/1262007838), [1262007843](https://www.openstreetmap.org/way/1262007843); but instead it goes around the square:

![image](https://github.com/GIScience/openrouteservice/assets/478237/c2b43143-f409-4be8-b727-b137d82466ac)

**Comment by aoles** [comment]
Hi @waldyrious,

First of all thank you for raising the issue and for opening a corresponding PR with a fix. 

While I understand your concerns, I don't believe this is actually a valid issue. This is so because routing on OSM ways tagged with `bicycle=destination` is not disabled in general. However,  transit traffic on ways tagged with access `destination` is forbidden and it is allowed to use the way only to reach a destination that can not be reached otherwise, see [OSM wiki](https://wiki.openstreetmap.org/wiki/Tag:access%3Ddestination). This is also the reason why the way is not used in your example. The described behaviour becomes evident once you choose a [via point](https://maps.openrouteservice.org/#/directions/R%20Jose%20Vidal%20Da%20Costa%2013,Braga,Portugal/Rua%20Am%C3%A9lia%20Bastos%20Leite,Braga,Portugal/R%20Dr%20Augusto%20Cesar%20Cerqueira%20Gomes%20123,Braga,Portugal/data/55,130,32,198,15,97,4,224,38,9,96,59,2,24,5,192,166,6,113,0,184,64,90,0,56,3,160,5,148,129,24,6,96,21,130,128,216,104,9,130,210,106,176,194,1,164,184,230,4,226,160,1,137,189,38,165,234,148,36,201,128,110,34,101,40,210,22,195,144,154,252,153,87,163,194,159,38,253,249,10,31,208,161,141,51,228,151,45,84,182,245,117,9,83,187,175,149,6,109,8,209,165,255,133,21,32,92,32,16,0,14,168,240,16,136,216,56,160,0,94,80,0,182,184,20,252,65,33,208,16,0,102,240,0,54,232,184,224,0,158,96,57,72,0,230,248,208,232,101,0,174,57,200,208,129,32,233,232,153,232,85,136,96,249,120,85,144,9,9,232,136,176,232,176,32,0,190,99,64,0) on the way in question. 

Cheers,
Andrzej

**Comment by waldyrious** [comment]
Oh, I see! Thanks for the explanation. I suppose the path is mistagged, then, as it is not forbidden to bike there. I'll fix the map. Cheers!

**Comment by aoles** [comment]
Thanks! Not sure either where the tagging comes from. I had a quick look via StreetView on the neighborhood in question but couldn't spot any signs limiting access to the square. As you said, it seems to be perfectly fine to take the shortcut.

![image](https://github.com/GIScience/openrouteservice/assets/6545356/7a8adccb-944d-4729-aac7-2e8e1794ecf8)
