### ISSUE TITLE
Geocododing using Nominatim instead of pelias

### ISSUE THREAD

**Issue by Namec** [GIScience/openrouteservice#182]
Hello,

can somesone share how can we figure out the changes that need to be made on the conf file, to make the geocoder engine to Nominatim

**Comment by rabidllama** [comment]
Hi @Namec 
we have actually updated the code recently so that the geocoding is separate from the main ORS code. At the minute this is in the development branch but should go into the master branch within the next month. So then the functionality to directly access a geocoder through the ors api will be removed.

At the minute, what you would need to do is to change the ``geocoder_name`` property to nominatim and then update the url properties to point to your instance of the nominatim database.

```
geocoding: {
				# Enables or disables (true/false) the end-point. Default value is true.
				enabled: true,
				# The name of a geocoder. Possible values are nomimatim, pelias or photon. 
            	                geocoder_name: pelias,
				# URL for forward geocoding.
                                geocoding_url: "http://YOUR_ADDRESS/v1/search",
				# URL for reverse geocoding.
                                reverse_geocoding_url: "http://YOUR_ADDRESS/v1/reverse",
				# The maximum allowed number of returned results.
                                response_limit: 20,
				#  Sets the value of the User-agent HTTP header sent to a backend.
                                user_agent: OpenRouteService,
                                attribution: "openrouteservice.org, OpenStreetMap contributors"
}
```

As we will be removing this soon however, I would recommend that you do not use the ors api geocoder but instead set up your own as you have to set up the Nominatim database anyway [(http://nominatim.org/release-docs/latest/admin/Installation/).](http://nominatim.org/release-docs/latest/admin/Installation/).

**Comment by TimMcCauley** [comment]
@Namec quick update - the geocoding code for proxying requests through ORS to nominatim/pelias/photon will stay in the core but we won't maintain it any longer, so feel free to set up your own instance and proxy requests through ORS.
