### ISSUE TITLE
Parsing error in way with OSMID=730310212 : Cannot parse duration tag value: 02:30;03:30

### ISSUE THREAD

**Issue by elipp** [GIScience/openrouteservice#1851]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

Using europe-latest.osm.pbf from Aug 4 2024 with the `openrouteservice/openrouteservice:v8.1.3` docker image, I noticed this line in the log output. Just wanted to notify in case someone already didn't.

Sorry if this is the wrong forum!

### Proposed solution

Investigate if this is a bug or a feature :D

**Comment by aoles** [comment]
Thanks for reporting the issue! :heart:

The problem for the [given way](https://www.openstreetmap.org/way/730310212) is that the [duration](https://wiki.openstreetmap.org/wiki/Key:duration?uselang=en) tag which represents ferry travel time contains an unsupported enumeration `02:30;03:30` rather than just a single value.

This is an OSM data problem. As such, it's beyond ORS scope to address it. Cheers!
