### ISSUE TITLE
General Rafael Urdaneta Bridge is not used as a dual carriageway when calculating directions

### ISSUE THREAD

**Issue by boromirmonk** [GIScience/openrouteservice#1873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem description

I am trying to plot in folium several routes that have as destination the city of Maracaibo in Venezuela. However, I see that when using and plotting on the map, none of the routes are using the bridge “Puente General Rafael Urdaneta” (10.579707281197996, -71.56902838614846) as a route option, which in effect would be the most optimal route, instead all the calculated routes are going around Lake Maracaibo:

`route = client.directions(coordinates=directions_coordinates, profile='driving-car', format='geojson', preference = 'shortest')`

However, something very strange happens, when using Maracaibo as the origin city, ors use the bridge to determine the shortest route.

### Proposed solution

The proposal is very simple, the bridge over Lake Maracaibo “General Rafael Urdaneta Bridge”, perhaps it should be modified so that it can be used as a dual carriageway when calculating routes, since it is only used in routes that go from west to east and not in routes that go from east to west.

### Additional context

https://maps.openrouteservice.org/#/directions/Caracas,DF,Venezuela/Maracaibo,ZU,Venezuela/data/55,130,32,198,15,97,4,224,38,9,96,59,2,24,5,192,166,6,113,0,184,64,90,0,217,8,14,128,78,1,24,7,96,3,150,128,104,40,1,132,129,88,157,98,128,89,8,27,159,42,20,74,18,104,91,163,22,132,120,6,100,42,196,61,16,16,0,58,167,129,17,54,28,160,1,121,64,11,107,140,162,229,208,32,3,55,128,6,221,46,16,177,163,192,6,228,128,57,190,48,201,160,41,10,125,57,244,104,116,68,48,91,60,32,200,125,125,96,216,116,88,16,0,95,4,160,0,0

**Comment by boromirmonk** [comment]
[Inverted route](https://maps.openrouteservice.org/#/directions/Maracaibo,ZU,Venezuela/Caracas,DF,Venezuela/data/55,130,32,198,15,97,4,224,38,9,96,59,2,24,5,192,166,6,113,0,184,64,90,1,216,4,96,14,128,54,0,25,206,32,22,0,105,140,162,219,200,25,156,129,88,6,231,220,243,72,4,230,40,64,7,24,198,205,58,84,231,92,136,122,32,32,0,117,79,2,34,108,57,64,2,242,128,22,215,32,197,203,160,64,6,111,0,13,186,92,33,99,71,128,13,201,0,115,124,97,147,64,82,20,250,115,232,208,232,136,96,182,120,65,144,250,250,193,176,232,176,32,0,190,9,64,0,0)

**Comment by MichaelsJP** [comment]
@boromirmonk Thanks for opening this. The problem is connected to taggings from the bridge.

When trying to access it from either side, it works when you move the start and endpoint closer to the bridge start.

![image](https://github.com/user-attachments/assets/edd397b5-783c-4512-ae2f-2ee2ac6f6816)

But when I try to route from start and end points further away from the bridge, there are clearly problems connected to the network and how ors deals with it.
I found two.

**The first problem:** The bridge entry is tagged with [a `barrier=lift_gate` tag next to a `barrier=toll_booth` ](https://www.openstreetmap.org/node/9711977536). A toll booth tag is fine and can be passed. But since the barrier is not tagged with `access=yes` ors must assume it's blocked. In general, it is new for me to see a combination of those barrier types directly behind each other. The toll booth would be enough in my opinion. As a reference, [a toll booth in Italy](https://www.openstreetmap.org/node/761415411), it also has lift gates, but that is, in my opinion, part of a toll booth.
![image](https://github.com/user-attachments/assets/38ef5750-a4f7-4a9d-af14-1cfdf69a0295)

**The second problem**: 
Ors can clearly bypass the toll booth. There appears to be a general osm network issue that could be addressed as well.
Once the toll booth is better mapped, this should not happen any more, but it still seems wrong that an external smaller road can bypass the toll booth via the U-turn lane from the opposite bridge lane. I don't know. Maybe the satellite image is outdated. Hard to tell.

![image](https://github.com/user-attachments/assets/5d20df2f-9fc5-4ab0-8481-dceb2f450fdc)
![image](https://github.com/user-attachments/assets/8f167099-058f-46f2-8711-eb0c09470be7)

**I just removed the double barriers.** With the next graph batch from ors it should not happen any more. **Please retry in a few days.**  [The changeset for the barrier removal.](https://www.openstreetmap.org/changeset/158570764)
[And here for the other side.](https://www.openstreetmap.org/changeset/158571105)

The weird road thing, I don't know. The bing image doesn't show it very well, and I'm not from the area. If you are, and you know more, please correct it. Closing this issue.

**Comment by boromirmonk** [comment]
The weird road thing looks like a return to the bridge, in case you are coming from the east side of the bridge to the west side and need to turn back. The route in the third picture is probably not permitted. Avenida Circunvalación is probably a highway type of avenue, and you probably won't be allowed to make that crossing in that short distance.

**Comment by boromirmonk** [comment]
Btw thanks for your help, I'll check next week to see if the issue persists.
