### ISSUE TITLE
Suggests a route through highway=construction

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [GIScience/openrouteservice#192]
To reproduce see [this route](https://maps.openrouteservice.org/directions?n1=50.085276&n2=19.857799&n3=16&a=50.091898,19.865427,50.084222,19.845504&b=1a&c=0&g1=-1&g2=0&h2=3&k1=en-US&k2=km).

A route is suggested through [a way](https://www.openstreetmap.org/way/463832906) with `highway=construction` - so a road that does not exist yet. There is no possibility even for a pedestrian to follow this way, but the route is suggested for bike and car.

Author: @pkubowicz

**Comment by rabidllama** [comment]
Normally the ORS does not route over construction roads, and in this case it is due to the "construction" tag only being added to the road in OSM 4 days ago and so it has not had enough time to be incorporated in our graphs. I have tested locally on the most recent OSM data for the area and the way is avoided, so it should be taken into account on the main ORS when the next global graphs are built.

**Comment by pkubowicz** [comment]
Thanks for checking. What is the approximate delay of picking OSM changes? I was mistaken by the fact that the map drawn in ORS was showing the OSM change - I assumed that route finding sees the same up-to-date data.

**Comment by rabidllama** [comment]
No problem. Normally we try to build the graphs every week at least, but recently we have had to make the gap a bit longer whilst we have been working on a few new things in the graphbuilding process. Hopefully they should all be up to the latest version within the next week though.

The reason for the difference between the map and routes is that as the base map we directly use the OSM map tiles which they generate and are very up to date, hence the differences that pop up sometimes.
