### ISSUE TITLE
Suggests a bicycle route against a one-way lane

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [GIScience/openrouteservice#193]
To reproduce see [this link](https://maps.openrouteservice.org/directions?n1=50.08111&n2=19.917263&n3=17&a=50.082446,19.913589,50.080863,19.917805&b=1a&c=0&g1=-1&g2=0&h2=3&k1=en-US&k2=km)

It is impossible to legally follow this route, as the bicycle path is connected to a one-way lane and lanes are separated (this can be seen in [OSM editor](https://www.openstreetmap.org/edit#map=19/50.08155/19.91640)).

author: @pkubowicz

**Comment by rabidllama** [comment]
I have checked and this appears to be due to the one way part of the road only being mapped on OSM 11 days ago and so our bicycle graphs haven't had chance to catch up with it. Using the latest dataset for the area on a local instance of ORS routes correctly, and so when the global bike graphs are updated, this change in OSM should be reflected in the routes.
