### ISSUE TITLE
Routing problem

### ISSUE THREAD

**Issue by gitka** [GIScience/openrouteservice#198]
Warum findet openrouteservice nicht den direkten Weg (Rennrad)?
https://maps.openrouteservice.org/directions?n1=48.549754&n2=12.092385&n3=15&a=48.55322,12.104509,48.546473,12.079511&b=1c&c=0&g1=-1&g2=0&h2=3&k1=en-US&k2=km

In diesem Fall, wäre die direkte Strecke auch die schnellste und auch die kürzeste Strecke über Wohngebietsstrassen - egal mit welchem Radtyp. Nur mit "E-Bike" wird die direkte Strecke gefunden.

**Comment by rabidllama** [comment]
The reason for taking the detoured route when generating the cycle route is due to elevation and gradient changes. In the cycling profiles, the graph generation tries to take into account the steepness of particular way segments and takes these into account when determining the speed of travel. In this particular case, the more direct route has much steeper segments to climb (up to 6%) and so it sees the more indirect but flatter route (there are only declines in it) as being the fastest. E-bike routes are not as concerned with inclines as the bike itself can help negate the problem of going uphill.

I hope that answers your question.

**Comment by gitka** [comment]
Thank you for your quick response. 
Even with a maximum steepness of 15% and choosing "mountain bike" I don't get the shortest and in my opinion the best way. 

For "Road bike" (fastbike) I would recommend to ignore a steepness up to 5% within 500 meters,

**Comment by rabidllama** [comment]
The issue with it taking the detoured route is not that it is trying to avoid steeper segments, it is that the steeper segments result in a much slower travel speed. So when the routing option is set to fastest, the routing algorithms see that taking the more detoured route which is flatter and so has less impact on speed results in a lower duration of the route than if the much slower incline segment was included.

The problem with ignoring steepness factor on segments of relatively short distances is that when the graph itself is built (which is when the steepness affects the speed) each segment is taken into account on its own. This means that if we were to ignore shorter segments, it could actually result in much longer ways having steepness ignored (as the full ways are made up of multiple small segments).
