### ISSUE TITLE
[Directions API] — Route to Closed Area

### ISSUE THREAD

**Issue by mkalygin** [GIScience/openrouteservice#207]
## Description

Hi!

There are some cases when a route cannot be properly built if a destination point is in a closed area.

Here is [an example route](https://maps.openrouteservice.org/directions?n1=60.004157&n2=29.715142&n3=14&a=59.93428,30.335099,59.996763,29.700944&b=4a&c=0&k1=en-US&k2=km).

The point B is in the closed area. And the route cannot reach this point because of that. Though it is possible to pass to the closed area. E.g. Yandex and Google can build this route correctly (see screenshots).

The OpenStreetMap.org result is different depending on the option choice: GraphHopper or OSRM. The GraphHopper one is the same as OpenRouteService. The OSRM one sometimes works correctly or doesn't build the route at all (see screenshots).

#### OpenRouteService

![image](https://user-images.githubusercontent.com/1662910/41913953-6378af3e-795a-11e8-9986-e25ba8a7821c.png)

#### Yandex

![image](https://user-images.githubusercontent.com/1662910/41913944-5c1d4056-795a-11e8-965a-770611ca9936.png)

#### OpenStreetMap

![image](https://user-images.githubusercontent.com/1662910/41913980-73a6d93a-795a-11e8-9210-38627e4df495.png)

**Comment by mkalygin** [comment]
@TimMcCauley any updates on this one? 🤔

**Comment by rabidllama** [comment]
Hi @mkalygin -I am having a look into this and so far it seems to be a problem with graphhopper itself as for some reason the whole of motorway going across the water is not being routed along...

**Comment by mkalygin** [comment]
@rabidllama thanks, do you have any idea how can we handle this? Do you use GraphHopper under the hood?

**Comment by rabidllama** [comment]
Yes our core routing uses the graphhopper libraries. At the minute I can't say for sure for a quick way around it as the problem seems to be rooted in the core of the graph building process, so it is taking a long time to debug. I will try to keep you informed of progress, but I can't give any definite timings yet.
________________________________

**Comment by rabidllama** [comment]
@mkalygin I think I have found the problem and it is actually the osm data rather than the routing.

Basically, on the motorway and nearby slip roads there are a lot of lifting gate nodes (barrier=lift_gate) such as https://www.openstreetmap.org/node/508239451 - when GH comes across these it sees them as potential barriers and because none of them have an access tag, it assumes that they cannot be passed. By taking that area of OSM and updating these nodes and adding the access=yes tag (which says that the public has a right to pass this barrier) the routing manages to go down that road

![image](https://user-images.githubusercontent.com/7126643/42637869-8269e996-85ec-11e8-8058-49f409522b44.png)

So to make it so that ORS (and graphhopper) can route down that motorway, and so to the destination specified, the original OSM data needs to be updated with the correct level of access to these barrier nodes (https://wiki.openstreetmap.org/wiki/Key:access and https://wiki.openstreetmap.org/wiki/Tag:barrier=lift%20gate?uselang=en-GB)

**Comment by mkalygin** [comment]
@rabidllama how can we achieve that and how can I help you?

**Comment by mkalygin** [comment]
@rabidllama any progress on this so far?

**Comment by rabidllama** [comment]
@mkalygin sorry I was away on holiday for two weeks. The only way it can be corrected is by updating the OSM data as it would not be correct for the routing to just ignore the presence of these gates. To properly follow the guidelines set by OSM, such information (whether the gate is publicly accessible) should be added by someone who has this information to hand or someone who actually knows these features (i.e. can physically see if they are accessible or not). If you know this area personally, then feel free to add the information mentioned in an above comment to reflect the actual state of the gate :)

**Comment by TimMcCauley** [comment]
Closing this one, @mkalygin please feel free to edit the OSM data directly.

**Comment by mkalygin** [comment]
@TimMcCauley I've edited the OSM data, but the API result from OpenRouteService doesn't seem to be updated properly. Is there any cache or something? This is the [result from GraphHopper]() and this is the [result from OpenRotueService](https://maps.openrouteservice.org/directions?n1=60.002408&n2=29.723365&n3=14&a=59.93428,30.335099,59.996665,29.701245&b=4a&c=0&k1=en-US&k2=km).

**Comment by rabidllama** [comment]
@mkalygin We have been having some technical difficulties lately with building new graphs, so the ones that are being used by ORS are a bit out of date. When we get them updated (hopefully within the next two weeks) the changes made should take effect.

**Comment by mkalygin** [comment]
@rabidllama Any help I can provide to speed up resolution of this issue? Is there any progress on this guy?

**Comment by rabidllama** [comment]
graphs are building as we speak (seems the problem we were having was in relation to a the docker tomcat image) and so if everything goes to plan, everything will be updated early next week

**Comment by mkalygin** [comment]
@rabidllama good news, this route is building almost correctly. It's already correct in [Graphhopper](https://graphhopper.com/maps/?point=60.009264%2C29.71318&point=59.997213%2C29.700616&locale=ru-RU&vehicle=car&weighting=fastest&elevation=true&ch.disable=true&use_miles=false&layer=Omniscale). But it's still not ideal in [OpenRouteService](https://maps.openrouteservice.org/directions?n1=59.997366&n2=29.703442&n3=17&a=60.006806,29.709891,59.997246,29.700678&b=4a&c=0&k1=en-US&k2=km). Still a cache issue? Or do I need to fix the map somehow?

**Comment by mkalygin** [comment]
@rabidllama unfortunately this hasn't been resolved yet. Could you reopen this bug? There are definitely some sync issues with Graphhopper's data.
