### ISSUE TITLE
Elevation = true parameter causes wrong route result

### ISSUE THREAD

**Issue by petrot** [GIScience/openrouteservice#21]
I recognized, that the elevation = true parameter kills the routing result. 
Sometimes tha last coord of the decoded polyline is [<good_value>, NaN].

My post config:

api_key: xxx
profile:driving-car
preference:fastest
language:hu
elevation:true
coordinates:20.1811515,46.2697751|20.14525,46.2738
options:{"avoid_features":"highways|tollways"}

**Comment by Rungee** [comment]
Hi Petrot,
Which library or piece of code have you used to decode a polyline?

**Comment by petrot** [comment]
Hi @Rungee,

I used this package: https://www.npmjs.com/package/polyline-encoded.

With geoJson output, it works fine.

**Comment by Rungee** [comment]
Now, the issue is clear to me.

Leaflet's implementation does not support elevation.

Check out the following two implementations taken from Leaflet and Graphhopper accordingly

1. https://gist.github.com/jieter/7689228
2. https://github.com/graphhopper/graphhopper/blob/469cf3c9634440e52821832c52280ca7e28322f4/web/src/main/java/com/graphhopper/http/WebHelper.java

If you need to support proper decoding of elevation values, you have to write your own decode function in js.

**Comment by TimMcCauley** [comment]
Mapbox currently also doesn't, I guess they would be happy about a PR ;) https://github.com/mapbox/polyline 

Considering this as closed.
