### ISSUE TITLE
Live Navigation using Continue Forward

### ISSUE THREAD

**Issue by farough** [GIScience/openrouteservice#24]
When using the Directions from ORS for live turn by turn directions, it is paramount to be able to allow the use of the user's current heading when coming up with directions. This prevents the user from needing to turn around because they went off the path which is a very jarring experience.

Preferably an input parameter would allow us to both specify the heading and the degrees of flexibility from this bearing we will accept in the new directions.

**Comment by TimMcCauley** [comment]
Will be live within the next 7 days.

**Comment by Rungee** [comment]
Very first implementation is done in 7513123949649a64f45a629d55fd22b299b63711.

**Comment by farough** [comment]
The feature in the API 4.3 does not support passing in a bearing to indicate the direction which to continue forward. Perhaps we have a miscommunication about the design of this feature.

**Comment by Rungee** [comment]
@farough , this issue is related to "continue_straight" parameter. 
The feature you are talking about is already implemented in #32 (see also #31). A complete description of the new features, in other words of the parameters "bearings" and "radiuses", will be provided within next week.

Closing this...
