### ISSUE TITLE
No route

### ISSUE THREAD

**Issue by ghost** [GIScience/openrouteservice#243]
I want to get the route from 9.260582,47.360331 to 9.283162,47.603291

If I avoid tracks and fords I get no route.
If I only avoid fords, I get is.
My expectation is that I can get in the route to the track, if I exclude this.

If I try this in the client (https://maps.openrouteservice.org) with avoiding tracks, I get the error "Es besteht keine Internetverbindung".

**Comment by aoles** [comment]
The problem is that your start point happens to lie along a [way tagged as `track`](https://www.openstreetmap.org/way/35221104).

Starting the routing only from the [crossing](https://www.openstreetmap.org/node/287703285) is currently not supported and would probably require substantial changes in the backend.

The spurious error message at maps.openrouteservice.org is a separate [issue](https://github.com/GIScience/openrouteservice-app/issues/235) already reported before.

**Comment by TimMcCauley** [comment]
@rschi instead of "no internet connection" the error message from the backend will appear in the next release on https://maps.openrouteservice.org which will basically tell you that no route can be found as @aoles has already explained 👍
