### ISSUE TITLE
Traffic data layer added to this tool set

### ISSUE THREAD

**Issue by llmuculusll** [GIScience/openrouteservice#264]
wie geht es ihnen in Heildelberg : )

 I do admire your work, it is quite state of the art.
 we are a team, concentrating on health sector problem-solving in Tehran, working on access and equality and urban population coverage.

We were wondering whether we can use traffic data layer added to this tool set.
 have you tried it? (since isochronous lines now are -as we checked- far from what happens in our city.)

 One pathway is adding hourly traffic of ordinary citizens;
 another ambitious one is analyzing the layer of pre-hospital ambulances transportation.

 Do you see it is feasible? Or super heavy developing should be done?
 All the best
 Arash

**Comment by rabidllama** [comment]
Hi @llmuculusll ,

We previously tried implementing some datasets regarding traffic into ORS but it gave mixed results and in the end we decided not to include it because of performance issues and availability of data. 

We don't have plans for redeveloping the code in the near future as it would not be a small job to get it working and in general, access to most traffic data is a pay-for service. It could be feasible in the future to introduce analysis based on user collected data, but that would be a particularly large task especially as we do not have any methods for collecting this data, so we currently have no plans for that sort of thing.

If you have a solution in mind though, feel free to fork the repository and experiment with it :) If it helps, the previously developed code can be found at https://github.com/GIScience/openrouteservice/tree/master/openrouteservice/src/main/java/heigit/ors/routing/traffic, but as I said, we currently have this feature switched off due to performance issues.

Regards
The ORS team
