### ISSUE TITLE
barriers with access:conditional block routing

### ISSUE THREAD

**Issue by eliboni** [GIScience/openrouteservice#293]
**Example1:**  access | motor_vehicle:conditional=yes @ (May-Oct)

https://www.openstreetmap.org/node/3165754680

But ORS refuse to cross it [link1](https://maps.openrouteservice.org/directions?n1=45.834231&n2=10.407243&n3=14&a=45.83353,10.396278,45.827636,10.39999&b=0&c=0&k1=en-US&k2=km)

**Example 2:**  access:conditional | no @ (Nov-Apr)

https://www.openstreetmap.org/node/4550696272

although it is "no @ (Nov-Apr)", as of today ORS refuse to pass through: [link2](https://maps.openrouteservice.org/directions?n1=46.213195&n2=11.421597&n3=15&a=46.213861,11.422348,46.20466,11.419601&b=0&c=0&k1=en-US&k2=km)

As a side note, I would love to be able to tell ORS to skip  "access:conditional" restrictions, this is preventing to use ORS to plan routes in the future (example, plan a  summer trip in Alps, Norway, Iceland etc during winter...)

**Comment by rabidllama** [comment]
At the minute we do not take into account temporal restrictions for routes and currently if the system detects a conditional temporal restriction, it is removed from the graph for safety reasons

**Comment by aoles** [comment]
> At the minute we do not take into account temporal restrictions for routes and currently if the system detects a conditional temporal restriction, it is removed from the graph for safety reasons

That's not entirely correct as actually the restrictions are being taken into account. The thing is that  they are resolved only at the time the graphs are being build. At the moment the above examples work even though the restrictions state that from November on these roads should be closed because we didn't update the graphs since October. These roads will be marked as impassable as soon as we rebuild the graphs.

However, I can already announce that a proper solution to temporal restrictions is on our roadmap for the next year, so stay tuned!
