### ISSUE TITLE
[Directions API] Consider destination as allowed access in barrier restrictions

### ISSUE THREAD

**Issue by mkalygin** [GIScience/openrouteservice#342]
This bug has been around for a while. The related issue #207 has been closed since initial problem was caused by the barriers on the roads in the area. But now when the barriers have been updated in OSM, the route is still wrong, though it has been partially updated. Similar Graphhopper route is fine. I'm thinking this could possibly be related to cache updates of ORS. Here are the routes:

- [OpenRouteService](https://maps.openrouteservice.org/directions?n1=59.997366&n2=29.703442&n3=17&a=60.006806,29.709891,59.997246,29.700678&b=4a&c=0&k1=en-US&k2=km)
- [Graphhopper](https://graphhopper.com/maps/?point=60.009264%2C29.71318&point=59.997213%2C29.700616&locale=ru-RU&vehicle=car&weighting=fastest&elevation=true&ch.disable=true&use_miles=false&layer=Omniscale)

Thanks for the hard work on the ORS API, it's great. I'm actively using it in my projects, so I'm willing to help here if needed.

**Comment by rabidllama** [comment]
The reason for this is that there are restrictions on the gates accessing that area that say it can only be passed for as a means of arriving at a destination that is within the gated area. It seems that other routing services are more relaxed with this whereas currently openrouteservice says that if the gate isn't marked as publicly accessible or accessible with permission, then you cannot go past it.

We will have discussions to see whether we should keep our current approach of completely restricting access or relax it to allow passage, but for now we will keep it as completely restricted due to legal reasons.

**Comment by rabidllama** [comment]
My initial thoughts on this would be to allow access through these "destination" barriers but include information somewhere that parts of the route are "restricted" (same would go for the "permissive" areas). The tricky thing here is that this information would have to be stored against the graph itself and then extracted during routing and added to the response.

**Comment by mkalygin** [comment]
@rabidllama just a thought here from the user's point of view... Wouldn't it be convenient to have it as an API parameter? Like some sort of flag telling the algorithm to be relaxed with routing through such barriers?

The problem is that `motor_vehicle=destination` means that this road is actually open if you travel to a particular destination (the Fort Constantine in this case). So at the very least I'd reconsider a set of prohibited `access` values for the routing.

**Comment by rabidllama** [comment]
The problem with exposing it as an optional parameter is that the point where the barrier is interpreted as an obstacle is at graph build time, which means that it is trickier (not impossible though) to store information about the type of access that is permitted. There seems to already be some code in place for this but I believe that there were problems with it so we need to look into what these problems were and how to address them. 

At the current state though it seems we are close to being able to provide information about what type of restrictions are being crossed in the extra_info section of the response, so it shouldn't be a complex task to do similar to Google and allow routing through those restricted areas but provide feedback about where these restrictions occur. Obviously this has some advantages in that it is easier for people to get a route, but at the same time it relies on them also taking note of the extra_info...

**Comment by rabidllama** [comment]
OK, I have been looking into this today and the main problem is that if we want to pass in the access restrictions in the api, it has to be what items to avoid as opposed to which to allow. During the graph building, the action is to include edges and then exclude them at request (like with the avoid features feature) but this does not work in revers (you cannot exclude an edge from the graph and then later say to include it...)

**Comment by mkalygin** [comment]
@rabidllama that's good news, thanks for looking at it. I like the idea of passing such option to the API and getting note about road access in `extra_info`.

**Comment by rabidllama** [comment]
So I think the best way forward for this at the minute is to remove the restriction on "destination" access items and then show any information about the restrictions via the extra_info. realistically dynamically setting what restrictions can be gone through via the api isn't currently feasible, simply because of it being the opposite of what is normally done (normally in the API you tell it what features to avoid rather than what not to avoid) and so implementing the logic behind that in the api and graph is quite a jump.

What I am currently looking into is having it so that when a route is generated and the access restriction extra storage is available, then it looks to see if there are any restricted segments and if so adds an "alert" message to the response and automatically returns the restrictions extra_info.

**Comment by mkalygin** [comment]
@rabidllama It makes sense. We can either remove the restriction by default and provide `extra_info` if there is any, or we can also add an opposite flag, something like `norestricted=true`. Actually I'd be happy only with the first part of this feature. The control of this over API sounds like a separate task.

**Comment by rabidllama** [comment]
Should be fixed now that we have updated to 4.7.2
