### ISSUE TITLE
Distance matrix with the ability of dynamic arguments (C-ALT + RPHAST)

### ISSUE THREAD

**Issue by TimMcCauley** [GIScience/openrouteservice#385]

**Comment by rabidllama** [comment]
We will need to look at this when the update with c-alt has been deployed

**Comment by stefanocudini** [comment]
hi i am using vroom and as ORS backend ..
I understand that vroom only uses the api matrix from ORS.

from what i understand the api matrix does not yet support dynamic parameters for the vehicle profile.

but in my use case I don't need to be dynamic for every request, because the profile of the vehicle I use is always the same.

I would like for example some predefined preference values, for example:
preference = 'shortest' instead 'fastest',
and some of these
restrictions = width = 3m, height = 2m, weight = 2.5t

can I make sure to enter these preferences for all requests to the api matrix? and therefore to have them also in the vroom result?

**Comment by stefanocudini** [comment]
my outputs is this.. ![Screenshot at 2020-03-26 17-56-26](https://user-images.githubusercontent.com/47107/77674300-a229b100-6f8b-11ea-99bc-8d9841870cff.png)

**Comment by stefanocudini** [comment]
![vroom](https://user-images.githubusercontent.com/47107/77674342-b9689e80-6f8b-11ea-86ce-abeef05e865c.png)

**Comment by nilsnolde** [comment]
No cross posting please @stefanocudini :

https://github.com/VROOM-Project/vroom/issues/310

**Comment by stefanocudini** [comment]
I'm sorry

I think I wrote here and afterwards I realized that perhaps it was better to write in the vroom project .. (the question is a little confusing)

**Comment by HendrikLeuschner** [comment]
On hold until other RE questions are resolved.

**Comment by koebi** [comment]
Does this get closed by #959 @HendrikLeuschner ?

**Comment by HendrikLeuschner** [comment]
yeah
