### ISSUE TITLE
Version number not incremented in pom.xml

### ISSUE THREAD

**Issue by heimpogo** [GIScience/openrouteservice#406]
#### Here's what I did
* `git checkout 4.7.2`
* Check the `<version>` information in `openrouteservice/pom.xml`.

#### Here's what I got
`4.7.0`

#### Here's what I was expecting
`4.7.2`

#### Here's what I think could be improved
The version information in the file should be the actual release number.

**Comment by rabidllama** [comment]
Hi @heimpogo - we don't normally increase the final number of the version in the pom as it changes the url of local requests, which would mean every time we do a release (normally once a month) we would have to update a number of things on local machines. In the newest version that will be coming soon (5.0) we will look at making it so that the pom only has the major and minor release version within it.

**Comment by heimpogo** [comment]
This will be very helpful. Thanks.
