### ISSUE TITLE
geometry_simplify does not work for > 2 locations

### ISSUE THREAD

**Issue by hhblaze** [GIScience/openrouteservice#457]
#### Here's what I did
Getting directions

[Getting directions with geometry_simplify=True](https://api.openrouteservice.org/directions?api_key=58d904a497c67e00015b45fc09d497d61a084b7988e14adafdb89594&coordinates=11.50306,53.33353|10.03285,53.56074|10.02152,53.55651|10.01092,53.55396|10.00315,53.55605|11.50306,53.33353&profile=driving-hgv&preference=fastest&format=json&units=m&language=en&geometry=True&geometry_format=polyline&geometry_simplify=True)

---
#### Here's what I got

{"error":{"message":"You cannot change an immutable PointList"},"info":{"engine":{"version":"5.0","build_date":"2019-02-28T08:13:19Z"},"timestamp":1552385578459}}
---
#### Here's what I was expecting

the nice result
---
#### Here's what I think could be improved
With geometry_simplify=False it works, please, check the function

**Comment by rabidllama** [comment]
Hi @hhblaze - we have recently been updating the api to get things like the simplify_geometry to work properly, and as such the **geometry_simplify=true parameter cannot be used on routes that have more than one segment** (in the Graphhopper core library I believe this is due to the simplify changing the geometry itself which can mess up aspects relating to via points). I have added an error message that says this is the case, so this should appear on the servers in the next few days. We will get it added to the documentation as well

**Comment by hhblaze** [comment]
Thank you!
