### ISSUE TITLE
30 minute isochrone excludes area around starting point

### ISSUE THREAD

**Issue by ivoburger** [GIScience/openrouteservice#468]
#### Here's what I did

I tried to generate 5 to 30 minutes (range 30 minutes, interval 5 minutes) isochrones for a place in Cyprus.
https://maps.openrouteservice.org/reach?n1=35.045457&n2=33.353462&n3=11&a=35.109851,33.384112&b=0&i=0&j1=30&j2=5&o1=1&o2=1&k1=en-US&k2=km
---
#### Here's what I got

The 30 minutes isochrone excludes some of the the 25 to 5 minutes isochrones area. Simply put, there is a hole in its middle. The other isochrones (25 to 5 min) seem ok.

![isochrones](https://user-images.githubusercontent.com/48688535/54546892-5114d380-49ad-11e9-9855-009d49bd1824.png)
---
#### Here's what I was expecting

I was expecting to get 5 to 30 minutes isochrones, each bigger one including the smaller ones' area.
---
#### Other observations:
The issue does not appear if only 30 min isochrone from the same starting point is generated.
https://maps.openrouteservice.org/reach?n1=35.037587&n2=33.385735&n3=11&a=35.109851,33.384112&b=0&i=0&j1=30&j2=30&o1=1&o2=1&k1=en-US&k2=km
If a starting point is shifted a bit, the issue disappears:
https://maps.openrouteservice.org/reach?n1=35.04883&n2=33.348656&n3=11&a=35.110922,33.382387&b=0&i=0&j1=30&j2=5&o1=1&o2=1&k1=en-US&k2=km
Same issue for a different place:
https://maps.openrouteservice.org/reach?n1=34.941158&n2=32.976092&n3=11&a=34.939352,32.975448&b=0&i=0&j1=30&j2=5&o1=1&o2=1&k1=en-US&k2=km

![isochrones2](https://user-images.githubusercontent.com/48688535/54547441-60e0e780-49ae-11e9-9cc3-2d05c03357ba.png)

**Comment by nilsnolde** [comment]
yeah, we'll have to do some work on the geometry of the isochrones, there's a few things going wrong here. Esp in areas with low street coverage. It's due to how it simplifies the actual geometry, i.e. build the alpha (or concave) shape. 

I'll leave this unassigned but add it to our TODO. Not sure yet who'll be best to take a look.

**Comment by rabidllama** [comment]
So a little update from what I can see about why this would happen (for when we get chance to look into it) - it does the hollow part because the distance between two of the points to the east are quite far from each other, and so the algorithm that generates the polygon basically creates a concave polygon as it thinks that this is the "better" way of doing it.

**Comment by MichaelsJP** [comment]
Fixed
