### ISSUE TITLE
Consider points with restrictions which belong to OSM ways

### ISSUE THREAD

**Issue by TimMcCauley** [GIScience/openrouteservice#49]

**Comment by TimMcCauley** [comment]
This will be added to the graphhopper osm reader fork on giscience

**Comment by karussell** [comment]
Do you mean barriers here?

**Comment by HendrikLeuschner** [comment]
Hi Peter,
this is a bug in the custom code which we use in our extended OSMReader that creates restriction storages, e.g. for height restrictions. See ORSOSMReader (onProcessWay) for that. The problem here is that in the (uncommon) case that a non-tower node has a restriction to it and is on top of a way, our storage does not process this information. Our current storage only directly processes OSMways, which means only tags associated directly with the way. See http://www.openstreetmap.org/node/1998647762 as and example. Our routing here does not process the maxheight tag.

**Comment by karussell** [comment]
Ah, ok. Thanks for the explanation.
