### ISSUE TITLE
Driving time is not realistic 

### ISSUE THREAD

**Issue by ifle** [GIScience/openrouteservice#546]
Consider driving on the following route. The real driver time is ~8-10min. But ORS give 4 min.
https://maps.openrouteservice.org/directions?n1=32.097618&n2=34.88613&n3=16&a=32.093391,34.874425,32.103044,34.896312&b=0&c=0&k1=en-US&k2=km

For example the OSRM give 5 min
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=32.0930%2C34.8745%3B32.1031%2C34.8965

And Graphhoper give 7 min, that very close to realistic.
https://www.openstreetmap.org/directions?engine=graphhopper_car&route=32.0930%2C34.8745%3B32.1031%2C34.8965

Is there Bicycle profile in ORS?

![image](https://user-images.githubusercontent.com/1140474/59411577-46a78180-8dc4-11e9-9ce2-43bf1d6e154c.png)

**Comment by HendrikLeuschner** [comment]
Real driving time is always a matter of when and who is driving. We currently do not support traffic information so that your driving time may differ due to high traffic. We are always working on optimizing the information processing to gain higher precision driving times. But subjective, singular driving times do not represent driving conditions throughout the day.
The bicycle profile can be enabled via the bike button that you have drawn a red rectangle around.
