### ISSUE TITLE
Error Code 2099 references always point 1

### ISSUE THREAD

**Issue by pathmapper** [GIScience/openrouteservice#567]
If a point can't be used for the routing, the Error Code 2099 references always point 1, regardless which point is causing the error (the coordinates shown in the error message are correct).

Example:

![auswahl_103](https://user-images.githubusercontent.com/20856381/36799234-f35bda1e-1cac-11e8-8258-77f6c1b1608c.png)

**Comment by pathmapper** [comment]
@sfendrich is this solved in the backend (and the app is not using an up-to-date version) or should this reopened here?

**Comment by sfendrich** [comment]
@pathmapper Sorry, I just forgot to reopen the issue when I transferred it.

**Comment by rabidllama** [comment]
So it seems this is basically due to how segments are handled. In the algo, each segment is calculated as a separate route, and so there are only ever two point references (0 for the start of the segment, and 1 for the end of the segment). If one segment of the route fails (i.e. cannot find a point), then an exception is thrown and the whole routing process terminated so that you don't end up with a mess of some found routes and some not. Because of that and the fact that the point not found error message comes from the GH library, the only thing that I can see is to add the segment number to the error message. That would mean in the above example, the message would be `Cannot find point 1: xxx xxx (segment 4)` and `Cannot find point 1: xxx xxx (segment 1)`

**Comment by pathmapper** [comment]
@rabidllama thanks for explaining the background.

It would be helpful if the error message would match the point labels (e.g. in the first example `A`, `1`, `2`, `3`, `B`), so the user could easy see which point is causing the termination of the routing process, especially if there are a lot of points used for a route.

Are the different route segments calculated sequentially? (segment 1, segment 2, segment 3,  ...)

If yes, maybe the following would be possible to implement:

**If number of segments = 1:**
Cannot find point 0 -> Error message: `Cannot find point A`
Cannot find point 1 -> Error message: `Cannot find point B`

**If number of segments = n (n > 1):**
Cannot find point 0 && segment 1 -> Error message: `Cannot find point A`
Cannot find point 1 && segment 1 -> Error message: `Cannot find point 1` (point matches segment) 
Cannot find point 1 && segment 2 -> Error message: `Cannot find point 2` (point matches segment) 
...
Cannot find point 1 && segment n -> Error message: `Cannot find point B`

**Comment by rabidllama** [comment]
That's what I originally thought about, but the error message itself (`Cannot find point 1: xxx xxx`) is constructed inside the GH library and all that comes out is an exception with a String message, so it could get a bit messy if we try to deconstruct the message and then replace values... I will continue to see if there is something that can be done which is a bit cleaner

**Comment by rabidllama** [comment]
I have put a fix in which will be part of the 5.0.2 release. To keep the array indexing consistent though, I have not used the A and B values as this is more a front end conversion than an API (it would likely be more useful for people using the API to use array IDs rather than a mix of letters and numbers)

**Comment by pathmapper** [comment]
@rabidllama cool, thanks!

> I have not used the A and B values as this is more a front end conversion than an API

Makes sense.

**Comment by rabidllama** [comment]
Fixed in Release 5.0.2
