### ISSUE TITLE
Routing true non-existing ramp

### ISSUE THREAD

**Issue by straend** [GIScience/openrouteservice#568]
#### Here's what I did

Routing errors, turning in on motorway on non-existing ramp, from the wrong direction

[Route request](https://maps.openrouteservice.org/directions?n1=60.471157&n2=22.364581&n3=17&a=60.457949,22.293149,60.469393,22.355676,61.496087,23.780974&b=0&c=0&k1=en-US&k2=km), Problem near the via-point. 

#### Here's what I got

<img width="959" alt="openroute-error" src="https://user-images.githubusercontent.com/1004231/61525045-5435d400-aa20-11e9-8874-89499370085b.PNG"> 
 
#### Here's what I was expecting

Route according the blue inpainting.

**Comment by rabidllama** [comment]
Hi @straend ,

this is a common issue (also #467, #397, #17) that occurs due to how the core algorithm (in GraphHopper) which generates routes quicker doesn't take into account turn restrictions. There will be a new update in the next few months that may address that issue, but we are still investigating the performance of that.

For now though, if you toggle the `Avoid road types` and choose one of those options, that forces it to use a slower algorithm where the turn restrictions are taken into account.

**Comment by MichaelsJP** [comment]
Is fixed
