### ISSUE TITLE
Isochrones not working

### ISSUE THREAD

**Issue by AgnesCT** [GIScience/openrouteservice#572]
I try to run isochrones and I get this error:

QGIS version: 3.8.0-Zanzibar
QGIS code revision: 11aff65f10
Qt version: 5.11.2
GDAL version: 2.4.1
GEOS version: 3.7.2-CAPI-1.11.0 b55d2125
PROJ version: Rel. 5.2.0, September 15th, 2018
Processing algorithm…
Algorithm 'Generate Isochrones' starting…
Input parameters:
{ 'INPUT_FIELD' : 'Name', 'INPUT_METRIC' : 0, 'INPUT_POINT' : None, 'INPUT_POINT_LAYER' : 'C:\\PROJECTS\\New_Shapefile.shx|layername=New_Shapefile', 'INPUT_PROFILE' : 1, 'INPUT_PROVIDER' : 0, 'INPUT_RANGES' : '15', 'OUTPUT' : 'TEMPORARY_OUTPUT' }

Traceback (most recent call last):
File "C:/Users/AC123/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ORStools\core\client.py", line 161, in request
blocking=True)
File "C:/Users/AC123/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ORStools\core\networkaccessmanager.py", line 259, in request
raise self.http_call_result.exception
ORStools.core.networkaccessmanager.RequestsException: Network error: Host not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:/Users/AC123/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ORStools\proc\isochrones_proc.py", line 249, in processAlgorithm
response = clnt.request(provider['endpoints'][self.ALGO_NAME], params)
File "C:/Users/AC123/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ORStools\core\client.py", line 170, in request
self._check_status()
File "C:/Users/AC123/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ORStools\core\client.py", line 223, in _check_status
if 400 < status_code < 500:
TypeError: '<' not supported between instances of 'int' and 'NoneType'

Execution failed after 0.05 seconds

I am not sure why.  I tried putting in a shp with points, I tried pointing to the area on the map canvas, I tried different transportation options, and same issue persists,

I have an API from ORS, thus it should be fine.  Please assist.

**Comment by nilsnolde** [comment]
Sorry, wrong repository, pls open here:
https://github.com/nilsnolde/orstools-qgis-plugin/issues

> I have an API from ORS, thus it should be fine. Please assist.

What does that mean? You're self-hosting?

More info please in the transferred issue:
- What's the URL you're requesting against? (*Web* -> *ORS Tools* -> *Provider Settings*)
- Copy/paste a full request (found in *View* -> *Panels* -> *Log Messages* after sending a request)
- What is the file you're putting in? `C:\PROJECTS\New_Shapefile.shx|layername=New_Shapefile` that's not how shapefiles work, `.shx` is more like an index file, no data in there. But that's not the problem here, the host error seems to be the problem

**Comment by AgnesCT** [comment]
My issue ended up being that I somehow deleted the URL I was requested from:

What's the URL you're requesting against? (Web -> ORS Tools -> Provider Settings)

Thank you!!!
