### ISSUE TITLE
GC overhead limit exceeded with own dataset

### ISSUE THREAD

**Issue by monishski** [GIScience/openrouteservice#638]
Hi there,

I am currently trying to rebuild ORS locally with my **own dataset** using Docker and encountered a Java **'GC overhead limit exceeded'** error. I am fairly inexperienced with Java and so I am struggling to understand the cause/solution of the problem. _[Note: it works fine with small/city level datasets!]_

I have searched both your **forums** and the **git issues** section and noted that others have encountered a similar problem, although their solutions appear to not be working for me. 

In particular, I am trying to build a map of Britain and Ireland.  The data comes from: 
https://download.geofabrik.de/europe/britain-and-ireland.html (1.2GB)

Below I list any changes I made to files in the ./docker folder to try to resolve the exception.

- **docker-compose.yml**

![image](https://user-images.githubusercontent.com/50742589/70855370-99700c00-1ec1-11ea-8357-d15fdf8d3edc.png)
**Note:** I tried amending/adding `-Xms2g -Xmx14g -XX:MaxMetaspaceSize=512m` after reading possible solutions in your forums. I have 16GB RAM (hence, I allocate the maximum heap space as 14GB - please correct me if I have misunderstood this!)

- **app.config.sample**

As I am only interested in the ''routing'' services, I set `enabled:false,` for "services" and "isochrones". 

Under "routing", under "profiles" I have the following:
```
"profiles": {
    "active":[
        "vehicles-car",
    ],
    ...
}
```
**Note:** I removed "vehicles-hgv", "bike", "pedestrian-walk" to avoid building unnecessary graphs...

- **Error message**

![image](https://user-images.githubusercontent.com/50742589/70855258-21edad00-1ec0-11ea-8c5d-c7196df7e58e.png)
**Note:** I tried to monitor the CPU usage using task manager and saw that 'Utilisation' percentage **initially** increase to ~ 60% when the ors-app container started running and before the error was raised (<5 mins) and also tried monitor it using `docker stats`, in which case I saw the 'CPU %' in the range of >100% but <200% before the error was raised and once the error was raised, the 'CPU %' dropped to ~ 0.5%.

Any help would be much appreciated!

**Comment by rabidllama** [comment]
Hi @monishski 
first thing to check is that it is actually assigning the correct heap space. if you change the logging line of the app.config file to `"level_file": "DEBUG_LOGGING.json",` that should provide a bit more info in the log output. What we are looking for is something along the lines of 
`03 Jan 08:31:16 INFO [routing.RoutingProfileManager] -  Total - 2 GB, Free - 12 GB, Max: 14 GB, Used - 616.01 MB`

If that shows lower numbers for max, then it means that the environment variables are not being passed across into docker, which is a known issue but should be fixed in the latest development branch (and I believe in master branch within the next week). So if that is the case, I would suggest building using the development branch rather than master to see if that fixes the issue. The other option is to not use docker (docker introduces a few things into the equation that can mess up memory usage) and instead build using maven and then deploy into a native tomcat installation.

**Comment by monishski** [comment]
Hi @rabidllama 

Sorry for my late response! I haven't played around with ORS for a while but I did end up seeing that that $JAVA_OPTS and $CATALONIA_OPTS were not being read...

I also did note that the latest development branch should overcome this problem!

Thanks a lot for your help... I look forward to playing around with it soon.
