### ISSUE TITLE
Hungarian language version ready

### ISSUE THREAD

**Issue by debyos** [GIScience/openrouteservice#641]
Dear All,

I have completed the Hungarian [translation](https://github.com/GIScience/openrouteservice-app/tree/development/app/languages) of Openrouteservice, you can find 
[the file here](https://github.com/GIScience/openrouteservice-app/files/4008609/hu-HU_json.zip).

Please, put it online.

(By the way, I have also translated it at [Google Spreadsheets](https://docs.google.com/spreadsheets/d/1GzFPlVrqJBmUatfWft7v-vS_tfENGtAy0RHOv_5n3SU/edit) but you can ignore it.)

Gábor

This Issue [can be found also here](https://github.com/GIScience/openrouteservice-app/issues/306), sorry for the confusion

**Comment by rabidllama** [comment]
Hi @debyos,
 
if I understand you correclty, the translations are for the front end and not the backend. The backend translation file for Hungarian can be found at https://github.com/GIScience/openrouteservice/blob/master/openrouteservice/src/main/resources/resources/locales/ors_hu-HU.resources.

I will close the issue here as it is related to the front end repository and not this one.
