### ISSUE TITLE
Missing languages

### ISSUE THREAD

**Issue by mariuszkrzaczkowski** [GIScience/openrouteservice#690]
Polish is translated but is not in the system by default, why?

https://docs.google.com/spreadsheets/d/1GzFPlVrqJBmUatfWft7v-vS_tfENGtAy0RHOv_5n3SU/edit#gid=0

https://github.com/GIScience/openrouteservice-app/#translations

> In this spreadsheet you can add a column for your language or check the already added words if they are correctly translated. Our service will be updated regularly with the latest language versions.

We checked and updated the translation so it's ok

**Comment by rabidllama** [comment]
That is because the process of adding languages to the backend routing service is different to the front end so adding it to one does not automatically add it to the other. So it just seems that the entry in the translation spreadsheet was missed by the backend group.

We have some instructions on our wiki (https://github.com/GIScience/openrouteservice/wiki/Contributing-Translations) if you would like to make a PR yourself, else we will add it when one of our developers has some available time.
