### ISSUE TITLE
Direction API isn't able to find some hiking routes

### ISSUE THREAD

**Issue by zugspitze** [GIScience/openrouteservice#731]
I am trying to find a hiking route from Watzmannhaus (a mountain hut in Bavaria) [47.571952, 12.933108]  to Watzmann (second highest mountain in Germany) [47.54916, 12.917093]. This hiking route is very famous and well known. The requested url is: [here](https://api.openrouteservice.org/v2/pdirections/foot-hiking/geojson?api_key=5b3ce3597851110001cf6248129cee2a6a9c40b29f8c88481189b9a7
)

---
Response:
`{"error":{"code":2010,"message":"Could not find point 1: 12.9169970 47.5479260 within a radius of 350.0 meters."},"info":{"engine":{"version":"6.1.0","build_date":"2020-05-25T04:51:11Z"},"timestamp":1590400934738}}`

---
Expectations:
A hiking route without error.

**Comment by aoles** [comment]
Thanks for reaching out! The route is not found because the [path between Hocheck and Watzmann](https://www.openstreetmap.org/way/32348311) is tagged with `sac_scale=demanding_alpine_hiking`, whereas ORS considers only trails up to T4 in terms of [sac scale](https://wiki.openstreetmap.org/wiki/Key:sac%20scale?uselang=en-US). See also https://github.com/GIScience/openrouteservice/issues/600#issuecomment-551053727.

**Comment by zugspitze** [comment]
@aoles Thanks for quick response. Is there an option to enable T5/T6 routing as well?

**Comment by aoles** [comment]
You're welcome. Unfortunately, there is such option available currently. As indicated in #600 I believe this might be implemented eventually, but not in the foreseeable future.
