### ISSUE TITLE
Inverted order of points results in different elevation

### ISSUE THREAD

**Issue by pathmapper** [GIScience/openrouteservice#770]
#### Here's what I did
`https://api.openrouteservice.org/v2/directions/cycling-regular/geojson`

body 1:
```js
{"coordinates":[[6.4342,51.195244],[6.437027,51.196705]],"elevation":"true"}
```

And the same request only with inverted order of the points.

body 2:
```js
{"coordinates":[[6.437027,51.196705],[6.4342,51.195244]],"elevation":"true"}
```

---
#### Here's what I got

output for body 1:
<img src="https://user-images.githubusercontent.com/20856381/87883582-bdbc3a00-ca08-11ea-9161-38b14a01a110.png" width="300"/>

output for body 2:
<img src="https://user-images.githubusercontent.com/20856381/87883632-083db680-ca09-11ea-8d46-19bd5fd687ed.png" width="320"/>

![ors_elevation_gif](https://user-images.githubusercontent.com/20856381/87883987-6ec3d400-ca0b-11ea-9b80-ee47815f69dd.gif)

---
#### Here's what I was expecting

Same elevation for the points of the returned linestring for both requests.

---
Maybe https://github.com/GIScience/openrouteservice/issues/625 is related.

**Comment by koebi** [comment]
[This forum thread](https://ask.openrouteservice.org/t/directions-api-returns-differnt-elevation-values-for-same-point-on-reverse-route/3707) has another example

**Comment by sfendrich** [comment]
The culprit is [this guy](https://github.com/GIScience/openrouteservice/blob/master/ors-engine/src/main/java/org/heigit/ors/routing/util/ElevationSmoother.java). It is probably also the reason for #625 and (at least partly) for #1470.

The smoothing actually changes the elevation of the way points in quite funny ways. The change depends on direction and also on the exact location of the points. So reversing the locations or moving start-, via- or end-points a little bit may change the elevation of other points. IMO this is not a desired solution.

Removing the smoothing might affect steepness calculations, hence, it may influence steepness difficulty weighting and the wheelchair profile in quite random ways (or should I write "might remove those random influences"?). As both steepness difficulty and wheelchair are rather prototypical, I would prefer removing smoothing for sake of reporting elevation consistently.

**Comment by rabidllama** [comment]
I think for wheelchair it doesn't use the elevation data for determining steepness as it is too course resolution, and instead relies on the OSM tags for steepness (at least from what I remember)

**Comment by sfendrich** [comment]
It seems that graphhopper already smoothes edges when reading OSM: [OSMReader.addEdge](https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/reader/osm/OSMReader.java#L315C25-L315C25).

**Comment by MichaelsJP** [comment]
Good find. It seems like in our current branch a similar logic is already present: https://github.com/GIScience/graphhopper/blob/ors_4.0/core/src/main/java/com/graphhopper/reader/osm/OSMReader.java#L863

@sfendrich Should we remove the post-processing and test out the native one?

**Comment by MichaelsJP** [comment]
I'd say let's remove our smoothing and try out the native one.

**Comment by aoles** [comment]
Fixed in https://github.com/GIScience/openrouteservice/pull/1511.
