### ISSUE TITLE
Calculated route ignoring "only straight ahead" property

### ISSUE THREAD

**Issue by suknuk** [GIScience/openrouteservice#897]
#### Here's what I did
Planning a route using ORS
https://maps.openrouteservice.org/#/directions/E40,Belgien/Avenue%20Chazal%20-%20Chazallaan,Belgien/data/55,130,32,198,15,97,4,224,38,9,96,59,2,24,5,192,166,6,113,0,184,64,22,0,233,240,1,128,14,18,4,224,9,159,74,200,29,129,155,232,6,128,86,19,11,61,129,24,73,32,25,145,187,106,131,168,3,100,30,192,55,17,97,149,242,240,229,199,187,117,12,66,177,1,0,3,170,120,17,19,97,202,23,116,8,0,205,224,1,183,75,132,44,104,240,1,185,32,14,96,22,140,50,104,90,67,155,162,91,163,67,162,33,131,217,226,134,64,2,216,197,134,195,162,195,248,1,121,64,198,226,241,144,2,251,101,0,0

---
#### Here's what I got
A route that ignored a "only straight ahead" property which is present in OSM

Here the position where a car is only able to go straight ahead:
![grafik](https://user-images.githubusercontent.com/7623515/114263808-f57c6f00-99e7-11eb-83f3-c437cc75fe77.png)

And the corresponding OSM link/position: https://www.openstreetmap.org/#map=19/50.84597/4.39220

---
#### Here's what I was expecting
A route which does not ignore a "only straight ahead" property.

When we inspect the point, we can see that there is a "straight ahead only" property in the point:
![grafik](https://user-images.githubusercontent.com/7623515/114263718-87d04300-99e7-11eb-8456-d1221e65b350.png)

---
#### Here's what I think could be improved
Routes taking into consideration these properties.

I am quite new to OSM in general so I'm not sure if I am able to fix this issue myself (if it is one? but I image yes), but I will have a look into the complexity of the service.

Using the two routing options for cars on the OSM website for the same route, OSRM does not ignore ignore this property:
![grafik](https://user-images.githubusercontent.com/7623515/114264062-01b4fc00-99e9-11eb-891e-24f1fce4eeda.png)
but GraphHopper does.

It should be notet that also the OSRM route is not the optimal one, only GoogleMaps comes up with the optimal solution in this case:
![grafik](https://user-images.githubusercontent.com/7623515/114264160-94559b00-99e9-11eb-8ece-a67ed76b9300.png)

**Comment by aoles** [comment]
Thanks for reaching out! Turn restrictions are currently not respected unless there are additional parameters such as `avoid_features=ferries` set in the query. This is so because the default when there are no options set  is to use the fastest CH routing algorithm which does not support turn restriction. As soon as any route filters are activated the backed switches to slower algorithm which supports turn restrictions. [Route with avoid ferries on]():

![image](https://user-images.githubusercontent.com/6545356/114379190-c81af700-9b88-11eb-9156-9c242134488d.png)
