### ISSUE TITLE
Foot-walking not working on localhost.

### ISSUE THREAD

**Issue by AvdylKrasniqi** [GIScience/openrouteservice#913]
Hi there,
Strangely, profile "`foot-walking`" doesn't return info on localhost while it does on official OSR API.
I also tried profile "driving-car" both on localhost and official API and it DOES return correct infos on the same entered coordinates.

The url: 
http://localhost:8080/ors/v2/directions/foot-walking?start=21.166191,42.667542&end=21.164099,42.667530
returns me:
`{"error":{"code":2099,"message":"Unable to get an appropriate route profile for RoutePreference = foot-walking"},"info":{"engine":{"version":"6.4.2","build_date":"2021-04-25T15:21:37Z"},"timestamp":1619365626305}}`

Notice that official OSR's API is version 6.4.1, meanwhile localhost API is version 6.4.2

**Comment by takb** [comment]
This error occurs because the profile is not activated in the `app.config` file. I assume you are using our Dockerfile, which is set up a bit counterintuitively to create a modified `app.config` based on the `app.config.sample` file. If you followed the instructions in the [README](https://github.com/GIScience/openrouteservice/blob/master/docker/README.md) you should see a directory named `conf` in the project root dir containing the `app.config` file that is actually used by the container. 
Please look for the array `ors.services.routing.profiles.active` in this file and add the profiles you want to use. After restarting the container, the profile should work.

**Comment by AvdylKrasniqi** [comment]
> This error occurs because the profile is not activated in the `app.config` file. I assume you are using our Dockerfile, which is set up a bit counterintuitively to create a modified `app.config` based on the `app.config.sample` file. If you followed the instructions in the [README](https://github.com/GIScience/openrouteservice/blob/master/docker/README.md) you should see a directory named `conf` in the project root dir containing the `app.config` file that is actually used by the container.
> Please look for the array `ors.services.routing.profiles.active` in this file and add the profiles you want to use. After restarting the container, the profile should work.

Oh, thanks for making it clear to me! Works like a charm!
