### ISSUE TITLE
Isochrones include areas that are not reachable (in  time)

### ISSUE THREAD

**Issue by DerDings** [GIScience/openrouteservice#972]
[Isochrones](https://maps.openrouteservice.org/reach?n1=51.472399&n2=7.30506&n3=12&a=51.467951,7.127166&b=0&i=0&j1=21&j2=7&k1=en-US&k2=km) include areas within the 14 minute zone which in fact are only reachable in 18 min when using [regular routing](https://maps.openrouteservice.org/directions?n1=51.481393&n2=7.197975&n3=12&a=51.467967,7.127107,51.466534,7.251277&b=0&c=0&k1=en-US&k2=km).
Same for a different location: [regular routing](https://maps.openrouteservice.org/directions?n1=51.482154&n2=7.302751&n3=11&a=51.468005,7.127108,51.463332,7.419752&b=0&c=0&k1=en-US&k2=km) says it takes 35 minutes, but the place is included in the [21 minute polygon](https://maps.openrouteservice.org/reach?n1=51.472399&n2=7.30506&n3=12&a=51.467951,7.127166&b=0&i=0&j1=21&j2=7&k1=en-US&k2=km).

This is probably because there are high speed roads all around which are reachable in this time. There needs to be a way to exclude ares from an isochrone, i.e. to make it a multipolygon.

A similar issue also appears for pedestrian routing: A location that takes [30 min to reach](https://maps.openrouteservice.org/directions?n1=51.501261&n2=7.309489&n3=15&a=51.504495,7.313971,51.499927,7.30608&b=2&c=0&k1=en-US&k2=km) is included in the [20 minute area](https://maps.openrouteservice.org/reach?n1=51.503667&n2=7.312474&n3=14&a=51.504462,7.313923&b=2&i=0&j1=30&j2=10&k1=en-US&k2=km).

This way, it is not possible to use the isochrones to find all the locations where a certain service isn't reachable in time. Also, the calculated reachable population is wrong because of this.

Screenshots in case there will be additional roads / speed limits in future:

![car isochrones](https://user-images.githubusercontent.com/42044179/107151356-770d3d80-6962-11eb-8832-f744e586c7a6.jpg)
![car route 1](https://user-images.githubusercontent.com/42044179/107151440-e5ea9680-6962-11eb-928d-4c8e09018563.jpg)
![car route 2](https://user-images.githubusercontent.com/42044179/107151433-dec38880-6962-11eb-9e9e-28d789b9fe84.jpg)
![pedestrian isochrones](https://user-images.githubusercontent.com/42044179/107151405-b20f7100-6962-11eb-8be3-b6fc091ad781.jpg)
![pedestrian route](https://user-images.githubusercontent.com/42044179/107151430-d9fed480-6962-11eb-821c-be2dc491d8dc.jpg)

**Comment by HendrikLeuschner** [comment]
This is a result of each isoline being calculated as a single Polygon rather than a MultiPolygon or a polygon with holes. So you are right, the inner areas are included because the surrounding areas are, even if they are not within the time limit.
This is the way the service is at the moment. Adding holes to polygons takes a lot of fine adjustments and performance optimizations, I have tried before. It will also never fulfill everyone's expectations, as the decision of whether a hole should exist at a certain place or not is subjective.
Feel free to contribute to the service for this, otherwise no change in the foreseeable future, sorry.
