### ISSUE TITLE
confusing error message for point not found in route with radiuses:[-1,..]

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [GIScience/openrouteservice#979]
#### Here's what I did

`https://api.openrouteservice.org/v2/directions/driving-car/geojson`
`{"coordinates":[[-5.723877,49.41461],[-5.614013671,49.18888421]],"radiuses":[-1,350]}`

---

#### Here's what I got

```
{
"error":{
  "code":2010,
  "message":"Could not find point 0: -5.7238770 49.4146100 within a radius of -1.0 meters."
},
"info":{
  "engine":{"version":"6.5.0","build_date":"2021-05-17T12:08:50Z"},
  "timestamp":1624360972143}
}
```

---
#### Here's what I was expecting

Something in the directon of `"Could not find opint 0: .... within the maximum possible search radius of 2500(?) meters"`
As `-1.0` meters is not really informative.

---
#### Here's what I think could be improved

The documenation states to put `-1` for radiuses to have **no limit** in the search.
The above error obviously states the opposite.

The documentation should be adjusted to state what is actually done.
Is this limit different for different profiles?

**Comment by koebi** [comment]
To me, it seems rather complicated and unclear what the actual limit used in that case is.

I'll clarify docs and warning, but it won't actually specify a radius in that case.

Maybe on refactoring in #985 this will get easier to implement, but in any case if this gets touched the error messages and docs should be looked over - which is why I'm mentioning this.
